# Generated by Django 3.0.5 on 2020-04-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('content', models.CharField(db_column='content', max_length=500, verbose_name='内容')),
            ],
            options={
                'verbose_name': '用户需求',
                'verbose_name_plural': '用户需求',
                'db_table': 'userDemand',
            },
        ),
    ]
