# Generated by Django 3.0.5 on 2020-04-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserManage', '0002_userdemand'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdemand',
            table='user_Demand',
        ),
    ]
