# Generated by Django 3.0.5 on 2020-05-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOrderManage', '0004_userpower'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpower',
            name='pay_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='支付名称'),
        ),
    ]
