# Generated by Django 3.0.5 on 2020-04-24 17:25

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('typename', models.CharField(db_column='typename', max_length=30, verbose_name='种类名称')),
                ('logo', models.CharField(db_column='logo', max_length=20, verbose_name='标识')),
                ('image', models.ImageField(db_column='image', upload_to='type', verbose_name='商品类型图片')),
                ('typeparent', models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='AppResourceManage.ResourceType', verbose_name='商品类别父类')),
            ],
            options={
                'verbose_name': '商品种类',
                'verbose_name_plural': '商品种类',
                'db_table': 'resource_type',
            },
        ),
        migrations.CreateModel(
            name='ResourceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('rname', models.CharField(db_column='name', max_length=100, verbose_name='资源名称')),
                ('rprice', models.DecimalField(db_column='price', decimal_places=2, default=1, max_digits=5, verbose_name='资源价格')),
                ('rdescribe', models.CharField(db_column='describe', default='无', max_length=2000, verbose_name='资源描述')),
                ('rdetail', tinymce.models.HTMLField(db_column='rdetail', null=True, verbose_name='资源详情')),
                ('is_logistics', models.BooleanField(db_column='is_logistics', default=False, max_length=2, verbose_name='是否需要物流')),
                ('rbaiduCloudAddress', models.CharField(db_column='baiduCloudAddress', default='无', max_length=200, verbose_name='云盘地址')),
                ('resource_type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.CASCADE, to='AppResourceManage.ResourceType', verbose_name='所属账户')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'db_table': 'resourceinfo',
            },
        ),
        migrations.CreateModel(
            name='IndexTypeRsourceBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('display_type', models.SmallIntegerField(choices=[(0, '标题'), (1, '图片')], default=1, verbose_name='展示类型')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppResourceManage.ResourceInfo', verbose_name='资源')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppResourceManage.ResourceType', verbose_name='资源分类')),
            ],
            options={
                'verbose_name': '主页分类展示资源',
                'verbose_name_plural': '主页分类展示资源',
                'db_table': 'index_type_goods',
            },
        ),
        migrations.CreateModel(
            name='IndexRsourceBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='图片')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('Resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppResourceManage.ResourceInfo', verbose_name='商品')),
            ],
            options={
                'verbose_name': '首页轮播商品',
                'verbose_name_plural': '首页轮播商品',
                'db_table': 'index_banner',
            },
        ),
    ]
