# Generated by Django 3.0.5 on 2020-04-24 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppResourceManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceinfo',
            name='resource_type',
            field=models.ForeignKey(blank=True, db_column='type', null=True, on_delete=django.db.models.deletion.CASCADE, to='AppResourceManage.ResourceType', verbose_name='类别'),
        ),
    ]
