# Generated by Django 3.0.5 on 2020-04-24 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppResourceManage', '0002_auto_20200425_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcetype',
            old_name='typename',
            new_name='type_name',
        ),
        migrations.RemoveField(
            model_name='resourcetype',
            name='typeparent',
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='type_parent',
            field=models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppResourceManage.ResourceType', verbose_name='类别父类'),
        ),
    ]
