# Generated by Django 3.0.5 on 2020-04-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppResourceManage', '0003_auto_20200425_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetype',
            name='image',
            field=models.ImageField(blank=True, db_column='image', null=True, upload_to='type', verbose_name='商品类型图片'),
        ),
    ]
