# Generated by Django 3.0.5 on 2020-04-24 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppResourceManage', '0004_auto_20200425_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexrsourcebanner',
            name='Resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppResourceManage.ResourceInfo', verbose_name='商品'),
        ),
    ]
